auto: true
server: true
markdown: kramdown
kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    default_lang: shell
highlighter: rouge

gist:
  noscript: false

lsi: false
safe: true
incremental: false
permalink: date

excludes:
  - Rakefile

libraries:
  ronin-support:
    name: ronin-support
    version: 1.0.0.beta1
    description: A support library for Ronin.

  ronin:
    name: ronin
    version: 2.0.0.beta1
    description: A Ruby toolkit for security research and development.

  ronin-core:
    name: ronin-core
    version: 0.1.0.beta1
    description: A core library for all ronin libraries.

  ronin-repos:
    name: ronin-repos
    version: 0.1.0.beta1
    description: Third-party git repository support for ronin.

  ronin-db-activerecord:
    name: ronin-db-activerecord
    version: 0.1.0.beta1
    description: ActiveRecord backend for the Ronin Database.

  ronin-db:
    name: ronin-db
    version: 0.1.0.beta1
    description:
      A common database library for managing and querying security data.

  ronin-web-server:
    name: ronin-web-server
    version: 0.1.0.beta1
    description: A custom Ruby web server based on Sinatra.

  ronin-web-spider:
    name: ronin-web-spider
    version: 0.1.0.beta1
    description: A collection of common web spidering routines.

  ronin-web-user_agents:
    name: ronin-web-user_agents
    version: 0.1.0.beta1
    description: Generates random but realistic User-Agent strings.

  ronin-web:
    name: ronin-web
    version: 1.0.0.beta1
    description: A collection of common web security commands and libraries.

  ronin-code-asm:
    name: ronin-code-asm
    version: 1.0.0.beta1
    description: A Ruby DSL for crafting Assmebly programs and Shellcode.

  ronin-code-sql:
    name: ronin-code-sql
    version: 2.0.0.beta1
    description: A Ruby DSL for crafting SQL Injections.

  ronin-post_ex:
    name: ronin-post_ex
    version: 0.1.0.beta1
    description: Ruby API for Post-Exploitation.

  ronin-payloads:
    name: ronin-payloads
    version: 0.1.0.beta1
    description:
      A Ruby micro-framework for writing and running exploit payloads.

  ronin-vulns:
    name: ronin-vulns
    version: 0.1.0.beta1
    description:
      Tests URLs for Local File Inclusion (LFI), Remove File Inclusion (RFI),
      SQL injection (SQLi), Cross Site Scripting (XSS), Server Side Template
      Injection (SSTI), and Open Redirects.

  ronin-exploits:
    name: ronin-exploits
    version: 1.0.0.beta1
    description:
      A Ruby micro-framework for writing and running exploits and payloads.

  ronin-fuzzer:
    name: ronin-fuzzer
    version: 0.1.0.beta1
    description: A highly configurable fuzzing library and CLI for Ruby.
